language: go
go:
  - 1.15.x
env:
  - GO111MODULE=on
arch:
  - amd64
  - arm
  - arm64
os: linux
script:
  - make build-travis
deploy:
  provider: releases
  api_key:
    secure: NfXAIan41QXbkecgI2hbfKNCj5aiV+yW+7EUaLi1qKTUjfMDBUYGc/fZuYxpKIVOkPHkKzP/gny/ByosIKq17MmzTl1s8vAG0fbEZPA1XPSQSB2boY4BVw73VOe7RtcQIImndJpV3IlFk5MUNXPXR7pCGwUYaBtgL/xuBty6LyuQeRNXKbkeQdXGYoa6kJGgS7dgQQYhH6K5I2MgpbKoP7sRubz781Q4SDcBF+61nLt49IbKAoOr2SDdLbSP7o9XMcVaGFNqjrLV/gYSW8xP2tRUZMG3vg11p7R4QoupQBhQ6hD7v17skQxZsZlCEAklH7VlN/ZfbV7D+OEsTQOpf42pyt1Q4/Byi339VXp35ea2bub881qVyQY4o2idIdfKB1LiqpAiLzu6g2RHxyyiaZ5Iwg/9YOWUBj4fekOlQP0rbzTHoB7BJXrgdd0bfi2A9ck2CFEHFKMdpncpAoZ89c8fu0wa3QWazcF6cI0KAyR9JrummdtlpfnhLFtWJi6q2RBaM4iDMD/+AtwQAsKdA1sxmfWHIWylJI2d7XhdCmb1mXOr1UMV7ESNbmVFHBhGbN+htkJ4yTz4BF2wj4f2dbnvHhMbGEtDz+8QyFZn1zFFtgVGQ8z/1WUlF+DXuycoEvCAPoD/1EFZxWGySxGzKAz1mtc/2hqWh6RB6YFOmj0=
  file_glob: true
  file: gohostsd-*
  skip_cleanup: true
  on:
    repo: inetAnt/gohostsd
    tags: true
